[package]
name = "amnesia-demo"
version = "0.1.0"
authors = ["Sebastian Schelter <ssc@apache.org>"]
edition = "2018"

[dependencies]
timely = "0.10.0"
differential-dataflow = "0.10.0"
rand = "0.4"
serde_json = "1.0"